### PR TITLE
Replace responsive layout and use dynamic props.

### PR DESCRIPTION
**Pull request by Hyperkid123**
### Description
Remove the default resposive layout and use "static" with dynamic props
- removes issues with conflicting breakpoint settings (screen vs parent)
description text...
- shortens debounce
- remove unnecessary mapping functions

Sort of depends on: https://github.com/RedHatInsights/chrome-service-backend/pull/513

### CODE REVIEW

**Comment by fhlavac** [comment]
Code looks good! Testing locally..

**Comment by fhlavac** [comment]
just `dashboard-templates.test.ts` is throwing an error since it is empty

**Comment by fhlavac** [comment]
@Hyperkid123 When moving the widgets and then resizing, the changes do not seem to be reflected
chrome-capture-2024-5-20

**Comment by epwinchell** [comment]
Old
Screenshot 2024-05-20 at 11 55 34 AM

New
Screenshot 2024-05-20 at 11 55 09 AM

**Comment by Hyperkid123** [comment]
@epwinchell ah thats probably because of the calculated with. I'll adjust it so it looks the same as before.

**Review by fhlavac — APPROVED** [review]
Looks great! Thank you @Hyperkid123 🎉  Everything seems to be working

**Review by epwinchell — APPROVED** [review]

**Pull request merged**
