### PR TITLE
Dependency commits tests

### PR DESCRIPTION
**Pull request by Hyperkid123**

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Me too

**Comment by InsightsDroid** [comment]
Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by Hyperkid123** [comment]
Foo bar

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.6.26) is older than required version (6.0.0)

**Pull request closed without merging**
