### PR TITLE
update custom layout to use encode/decode service

### PR DESCRIPTION
**Pull request by InsaneZein**
for [RHCLOUD-31664](https://issues.redhat.com/browse/RHCLOUD-31664) and [RHCLOUD-31448](https://issues.redhat.com/browse/RHCLOUD-31448)

encodedecodecustomlayout

### CODE REVIEW

**Comment by InsaneZein** [comment]
This is very close to being completed. Currently there is an issue where decoding the encoded string throws this error: 
`{
    "errors": [
        "invalid grid item, layout variant sm, width must be less than or equal to 1"
    ]
}`

**Comment by InsaneZein** [comment]
I've also added string validation
validation
n

**Review by aferd — APPROVED** [review]

**Comment by fhlavac** [comment]
@InsaneZein just curious, do we really want to re-add the dropdown? The default/custom layout switch has no effect now, right?

**Comment by fhlavac** [comment]
When I paste a valid configuration and then add some characters to make it invalid, it still shows a valid state. Maybe we want to validate on change with the use of some debounce?

**Comment by Hyperkid123** [comment]
The dropdown no longer makes sense as per the latest discussion with UX. I think this whole thing needs to be re-visited.

**Comment by InsaneZein** [comment]
I showed it to Mary on Thursday and she thought there should still be a default layout option in the drop-down. I do think we should open up a discussion with UX about this though.

**Comment by karelhala** [comment]
No longer relevant. We'll revisit the copy later on.

**Pull request closed without merging**
